---
development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password: postgres
  database: squash_development
test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password: postgres
  database: squash_test
production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password: postgres
  database: squash
  pool: 30
